# =========================================================
# Project Titanio - update_em_massa.py
# Converts an Excel (.xlsx) file into an optimized SQL Server update
# Uses a temporary table (#temp) for efficiency
# Resolves collation conflicts using COLLATE
# Generates a report of ignored rows and missing documents
# =========================================================

import pandas as pd
import os

# ==============================
# CONFIGURATION
# ==============================
excel_file = "dados.xlsx"           # Input Excel (same folder as script)
sql_output_file = "update_em_massa.sql"  # Output SQL file
table_name = "SIGFLU"
col_doc = "DCTO"
col_bank = "numero_port"

records = []   # Valid records
ignored = []   # Rows with invalid bank number

# ==============================
# READ EXCEL FILE
# ==============================
if not os.path.isfile(excel_file):
    print(f"❌ File not found: {excel_file}")
    exit(1)

df = pd.read_excel(excel_file, engine='openpyxl', header=0)
df.columns = [str(col).strip() for col in df.columns]

print("Detected columns:", df.columns.tolist())

# ==============================
# PROCESS ROWS
# ==============================
for _, row in df.iterrows():
    doc = str(row['Numerodedocumento']).strip()
    try:
        bank = str(int(float(row['Numerobancario']))).strip()
    except (ValueError, TypeError):
        ignored.append([doc, row['Numerobancario']])
        continue

    # Escape single quotes in document
    doc = doc.replace("'", "''")

    records.append((doc, bank))

if not records:
    print("❌ No valid records found. Exiting.")
    exit(1)

# ==============================
# GENERATE SQL
# ==============================
with open(sql_output_file, "w", encoding="utf-8") as f:
    f.write("-- =========================================================\n")
    f.write("-- Project Titanio - SQL generated by update_em_massa.py\n")
    f.write(f"-- Total valid records: {len(records)}\n")
    f.write("-- =========================================================\n\n")
    f.write("BEGIN TRANSACTION;\n\n")

    # Create temporary table
    f.write("CREATE TABLE #temp (DCTO NVARCHAR(50), numero_port NVARCHAR(20));\n\n")

    # Insert all records at once
    f.write("INSERT INTO #temp (DCTO, numero_port) VALUES\n")
    f.write(",\n".join([f"    ('{doc}', '{bank}')" for doc, bank in records]))
    f.write(";\n\n")

    # Update main table using temp table with COLLATE to avoid collation conflict
    f.write(f"UPDATE t\nSET t.{col_bank} = temp.numero_port\nFROM {table_name} t\n")
    f.write(f"JOIN #temp temp ON t.{col_doc} COLLATE SQL_Latin1_General_CP1_CI_AS = temp.DCTO COLLATE SQL_Latin1_General_CP1_CI_AS;\n\n")

    # Missing documents report
    f.write("-- =========================================================\n")
    f.write("-- Missing documents report (not found in table)\n")
    f.write("-- =========================================================\n")
    f.write(f"SELECT temp.DCTO\nFROM #temp temp\n")
    f.write(f"LEFT JOIN {table_name} t ON t.{col_doc} COLLATE SQL_Latin1_General_CP1_CI_AS = temp.DCTO COLLATE SQL_Latin1_General_CP1_CI_AS\n")
    f.write(f"WHERE t.{col_doc} IS NULL;\n\n")

    # Drop temp table
    f.write("DROP TABLE #temp;\n\n")
    f.write("COMMIT;\n")

# ==============================
# PRINT IGNORED ROWS
# ==============================
print(f"✅ Optimized SQL script generated with {len(records)} records!")
if ignored:
    print(f"⚠️ {len(ignored)} records were ignored (invalid or missing bank number):")
    for row in ignored:
        print(f"  {row}")